[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "public"

[functions]
  included_files = ["views/**/*", "include/**/*", "component/**/*"]

[dev]
  command = "npm run dev:netlify"

# 정적 파일들 직접 서빙
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/scss/*"
  to = "/scss/:splat"
  status = 200

[[redirects]]
  from = "/js/*"
  to = "/js/:splat"
  status = 200

# 모든 동적 요청을 functions로 리다이렉트
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app/:splat"
  status = 200 